### ISSUE TITLE
 Questions about enable_materialized_views and enable_transient_replication

### ISSUE THREAD

**Issue by ghost** [femiwiki/cassandra#3]
Thanks for providing this useful container! I have a question about two cassandra configs: `enable_materialized_views` and `enable_transient_replication.` It seems the [official document](http://cassandra.apache.org/doc/latest/configuration/cassandra_config_file.html)
does not recommend to enable them in production but you set that to be enabled in  `/etc/cassandra/cassandra.yaml`:

![image](https://user-images.githubusercontent.com/4555674/56547979-b8392100-6533-11e9-9347-aafdfaef4721.png)

Shall we disable them?
Thanks!

**Comment by simnalamburt** [comment]
Thanks for the good recommendation. I think it's good idea! Actually this image's `/etc/cassandra/cassandra.yml` contains many inappropriate configurations for production (e.g. #2), so there'll be quite many to fix.

By the way please note that this docker image is specifically designed for <femiwiki.com>. We may introduce backward-incompatible or femiwiki specific changes to this image. Actually, we already have bunch of femiwiki specific codes 😅

**Comment by ghost** [comment]
Thanks for your response!

The default value for these two parameters are already changed to `False` in the [document](http://cassandra.apache.org/doc/latest/configuration/cassandra_config_file.html). And is changed in the code for Cassandra 4.

However, in the latest version of Cassandra (3.11.4), the default value for them are still True. We may disable them manually for now.
Thanks!
